<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitab7ecc8af3049dd4e29e505ec4cb4c1d
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Lablnet\\' => 8,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Lablnet\\' => 
        array (
            0 => __DIR__ . '/..' . '/lablnet/hashing/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab7ecc8af3049dd4e29e505ec4cb4c1d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab7ecc8af3049dd4e29e505ec4cb4c1d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
